### ISSUE TITLE
Unable to run project - meteor version file missing

### ISSUE THREAD

**Issue by riaan53** [vsivsi/meteor-file-job-sample-app#1]
Hi,

What version was this project done in? The release file is missing? It looks like pre-version 0.9.

Thanks,

Regards,
Riaan

**Comment by vsivsi** [comment]
@riaan53 Hi, I'm just recently back from vacation. Thanks for this question and for the other work you've done on other topics. I'll start working on these tomorrow. Thanks for your patience!

**Comment by vsivsi** [comment]
An old, old version.  I'll bring this up-to-date tonight. Thanks for catching this issue.

**Comment by vsivsi** [comment]
Hi @riaan53, I think I got this sample project all up-to-date with the latest everything. Please check it out and let me know if it works for you now.  Thanks, -V

**Comment by riaan53** [comment]
Hi @vsivsi ,

Thank you for the updated package. Im unfortunately still getting an error at start-up. See below:

```
Riaans-MacBook-Pro:meteor-file-job-sample-app riaan$ meteor
[[[[[ ~/Projects/meteor-file-job-sample-app ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  

   While selecting package versions:
   error: unknown package: npm-container

=> Your application has errors. Waiting for file change.
```

Do you know what is causing it?

Regards,
Riaan

**Comment by vsivsi** [comment]
I forgot to commit the packages directory necessary for the npm-container to work.  Please try again with the latest commit.  Thanks, -V

**Comment by riaan53** [comment]
It works 100%, 

Thanks!

**Comment by vsivsi** [comment]
@riaan53 Great! Glad it works for you now, enjoy!
